# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2bb3d29339278a48be3ec6d93329f538744b434c59e796bca5e1ace971d5c9ccd5fe43b987fe0ecb97501c5872053175ab3d30ab6d7065c4307a3e137420ea74

test:
  secret_key_base: de0bd041880f502a02a37ad51651de749e4eebb05eb93ec462683df801218ada57d48a0608736d51f3914ec0966b373b77de58e141a87856fb034677c9eb29f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
